### ISSUE TITLE
[FEATURE REQUEST] - Delete original files that have been encrypted

### ISSUE THREAD

**Issue by KolyaKorruptis** [Arctosoft/Valv-Android#23]
The user intent is clearly to hide the files they encrypt. Leaving the original unencrypted files lying around is opposed to that intent.
At best it's an inconvenient extra step for the user to find and delete them in a file management app. At worst it's a security issue if they don't notice or forget. Therefore original files that have been successfully encrypted should get immediately deleted.

**Comment by ricassiocosta** [comment]
Just an additional information to this request: The auto delete mechanism should use a shredder strategy to avoid data recovery. A random data overwrite + 0s overwrite would be enough (the last run should be using 0s, instead of random data, because random data usually means that some encrypted file is being hidden).
