### ISSUE TITLE
[FEATURE REQUEST] - Shred original files after importing

### ISSUE THREAD

**Issue by hej2010** [Arctosoft/Valv-Android#47]
From https://github.com/Arctosoft/Valv-Android/issues/23#issuecomment-1950223767:

> The auto delete mechanism should use a shredder strategy to avoid data recovery. A random data overwrite + 0s overwrite would be enough (the last run should be using 0s, instead of random data, because random data usually means that some encrypted file is being hidden).

**Comment by ricassiocosta** [comment]
By the answer of this question here https://github.com/Arctosoft/Valv-Android/discussions/50, the app cache deletion should also be shredded on vault lock.

**Comment by hej2010** [comment]
It seems like it is difficult to permanently delete/shred files on Android:
https://security.stackexchange.com/a/185627
https://stackoverflow.com/a/38518260/7232269

Maybe the best way is to not use the disk cache at all and only read directly from the encrypted files (and use the memory cache)

**Comment by clach04** [comment]
> By the answer of this question here #50, the app cache deletion should also be shredded on vault lock (if possible).

I think a cache is a bad idea. Opened #95

**Comment by clach04** [comment]
> From [#23 (comment)](https://github.com/Arctosoft/Valv-Android/issues/23#issuecomment-1950223767):
> 
> > The auto delete mechanism should use a shredder strategy to avoid data recovery. A random data overwrite + 0s overwrite would be enough (the last run should be using 0s, instead of random data, because random data usually means that some encrypted file is being hidden).

Shredding / memory overwriting is definitely a good idea.

I'm not sure File shredding / over writing is worth doing on memory back storage like SD cards, MMC, etc. that Android uses for storage, due to [wear leveling](https://en.m.wikipedia.org/wiki/Wear_leveling). I'm not sure you can overwrite those exact bytes in the same location "on disk". This is not my area of expertise though so this is definitely an [armchair opinion](https://en.m.wikipedia.org/wiki/Armchair_theorizing) 😆 

Shredding is a great idea on spinning media 😀
